# https://api.github.com/repos/SolidStonee/UGGReleases/releases
# on:
#   push:
#   pull_request:
#   workflow_dispatch:

# jobs:
#   build:
#     name: tsc
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup
#         uses: actions/setup-dotnet@v2
#         with:
#           dotnet-version: 5.0.x

#       - name: Download
#         uses: dsaltares/fetch-gh-release-asset@master
#         with:
#           repo: "SolidStonee/UGGReleases"
#           version: "tags/1.0.9"
#           file: "UGG.1.0.9.rar"
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Generate
#         uses: tetra-fox/ml-gen@latest
#         with:
#           game: among-us
#           game_path: ${{ github.workspace }}/Among Us
#           game_executable: Among Us

